#include "constants.h"
#include "util/util.h"

namespace Constants {
const int FRAME_DELAY =
    1000 / 30;  // The number of milliseconds in a second divided by FPS
const int WINDOW_SIZE = 768;    // The size of the GUI window (736 x 736)
const int CHARACTER_SIZE = 64;  // The size of the character (64 x 64)
const int CHARACTER_MOVEMENT_GAP =
    20;  // The number of pixels to move the character
const int ATTACK_RANGE = 100;
const char* CHARACTER_ELF_DOWN_FOLDER_PATH = "assets/characters/elf/down/";
const char* CHARACTER_ELF_LEFT_FOLDER_PATH = "assets/characters/elf/left/";
const char* CHARACTER_ELF_RIGHT_FOLDER_PATH = "assets/characters/elf/right/";
const char* CHARACTER_ELF_UP_FOLDER_PATH = "assets/characters/elf/up/";
const char* MAP_TILE_SET_PATH = "assets/map/tile_set.png";
const int MAP_TILE_WIDTH = 16;
const int MAP_TILE_HEIGHT = 16;
const int SPRITE_SCALE = 3;
const int TILE_MAP_DATA[MAP_TILE_WIDTH * MAP_TILE_HEIGHT] = {
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(1, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 4), Util::GetTileIndex(1, 4),
    Util::GetTileIndex(2, 4), Util::GetTileIndex(3, 4),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 4), Util::GetTileIndex(1, 4),
    Util::GetTileIndex(2, 4), Util::GetTileIndex(3, 4),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 4), Util::GetTileIndex(1, 4),
    Util::GetTileIndex(2, 4), Util::GetTileIndex(3, 4),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 4), Util::GetTileIndex(1, 4),
    Util::GetTileIndex(2, 4), Util::GetTileIndex(3, 4),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 4), Util::GetTileIndex(1, 4),
    Util::GetTileIndex(2, 4), Util::GetTileIndex(3, 4),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 4), Util::GetTileIndex(1, 4),
    Util::GetTileIndex(2, 4), Util::GetTileIndex(3, 4),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 4), Util::GetTileIndex(1, 4),
    Util::GetTileIndex(2, 4), Util::GetTileIndex(3, 4),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
    Util::GetTileIndex(0, 4), Util::GetTileIndex(1, 4),
    Util::GetTileIndex(2, 4), Util::GetTileIndex(3, 4),
    Util::GetTileIndex(0, 0), Util::GetTileIndex(1, 0),
    Util::GetTileIndex(2, 0), Util::GetTileIndex(3, 0),
    Util::GetTileIndex(0, 1), Util::GetTileIndex(1, 1),
    Util::GetTileIndex(2, 1), Util::GetTileIndex(3, 1),
    Util::GetTileIndex(0, 2), Util::GetTileIndex(1, 2),
    Util::GetTileIndex(2, 2), Util::GetTileIndex(3, 2),
    Util::GetTileIndex(0, 3), Util::GetTileIndex(1, 3),
    Util::GetTileIndex(2, 3), Util::GetTileIndex(3, 3),
};
}  // namespace Constants